version: "3.7"
services:


  ##############
  ## Services ##
  ##############

  edge:
    image: dgoldstein1/edge-dev
    build:
      context: .
      dockerfile: ./docker/edge/dockerfile
    ports:
      - 8443:80
    restart: always

  links:
    image: links-ui:dev
    build:
      context: .
      dockerfile: docker/links-dev/dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - REACT_APP_ENV=development
      - REACT_APP_TWOWAYKV_ENDPOINT=/services/twowaykv
      - REACT_APP_BIGGRAPH_ENDPOINT=/services/biggraph
    depends_on:
      - kv
      - graph

  kv:
    image: dgoldstein1/twowaykv:1.0.0
    ports:
      - 5001:5001
    depends_on:
      - prom

  graph:
    image: dgoldstein1/biggraph:0.1.4
    ports:
      - 5000:5000
      - 8001:8001
    depends_on:
      - prom
    environment:
      - GRAPH_SAVE_PATH=/data/wikipedia_graph.graph
      - GRAPH_SAVE_INTERVAL=60

  ################
  ## Monitoring ##
  ################

  prom:
    image: prom/prometheus:v2.11.1
    ports:
      - 9090:9090
    entrypoint: "/bin/prometheus --log.level=debug --config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:6.2.4
    volumes:
      - ./docker/grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - prom
    ports:
    - "3001:3000"
