version: "3.7"
services:


  ##############
  ## Services ##
  ##############

  # crawler:
  #   image: dgoldstein1/crawler:1.1.0
  #   depends_on:
  #     - kv
  #     - graph
  #   environment:
  #     - GRAPH_DB_ENDPOINT=http://graph:5000
  #     - TWO_WAY_KV_ENDPOINT=http://kv:5001
  #     - MAX_APPROX_NODES=100
  #     - COMMAND=s
  #     - METRICS_PORT=8001
  #     - PARALLELISM=1
  #     - MS_DELAY=1000
  #     - STARTING_ENDPOINT=

  edge:
    image: dgoldstein1/edge-dev
    build:
      context: .
      dockerfile: ./docker/edge/dockerfile
    ports:
      - 3005:80
    restart: always

  # links:
  #   image: links-ui:dev
  #   build:
  #     context: .
  #     dockerfile: docker/links-dev/dockerfile
  #   environment:
  #     - REACT_APP_ENV=development
  #   volumes:
  #     - ./:/usr/src/app

  # uncomment for prod
  links:
    image: dgoldstein1/links:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      # configure reverse-proxy
      - PORT=3000
      - services=biggraphdev,twowaykvdev,geoip,lookupdev,analytics,grafana,prometheus,links,biggraphcounties,twowaykvcounties,lookupcounties
      ###################
      ## core services ##
      ###################
      - links-bundle_incoming_path=/
      - links-bundle_outgoing_url=file:///static-files
      #################
      ## dev backend ##
      #################
      - biggraphdev_incoming_path=/services/dev/biggraph/
      - biggraphdev_outgoing_url=http://graph:5000
      - twowaykvdev_incoming_path=/services/dev/twowaykv/
      - twowaykvdev_outgoing_url=http://kv:5001
      - lookupdev_incoming_path=/services/dev/wiki/
      - lookupdev_outgoing_url=https://en.wikipedia.org
      ######################
      ## counties backend ##
      ######################
      - biggraphcounties_incoming_path=/services/counties/biggraph/
      - biggraphcounties_outgoing_url=http://graph-counties:5000
      - twowaykvcounties_incoming_path=/services/counties/twowaykv/
      - twowaykvcounties_outgoing_url=http://kv-counties:5001
      - lookupcounties_incoming_path=/services/counties/wiki/
      - lookupcounties_outgoing_url=https://en.wikipedia.org
      ###############
      ## analytics ##
      ###############
      - geoip_incoming_path=/analytics/api/geoIpServer/
      - geoip_outgoing_url=https://geo.ipify.org/api/
      - analytics_incoming_path=/analytics/server/
      - analytics_outgoing_url=http://analytics-server:5000
      ###########
      ## admin ##
      ###########
      - grafana_incoming_path=/admin/grafana/
      - grafana_outgoing_url=http://grafana:3000
      - prometheus_incoming_path=/admin/prometheus/
      - prometheus_outgoing_url=http://prom:9090
    depends_on:
      - kv
      - graph

  kv-counties:
    image: dgoldstein1/twowaykv:1.0.1
    ports:
      - 5001:5001
    depends_on:
      - prom

    environment:
      - USE_S3=true
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_KV_PATH=s3://links-deployment/counties/twowaykv/counties
      # - AWS_KV_PATH=s3://links-deployment/synonyms/twowaykv
      - AWS_SYNC_DIRECTORY=s3://links-deployment/counties/twowaykv/counties
      # - AWS_SYNC_DIRECTORY=s3://links-deployment/synonyms/twowaykv
      - GRAPH_DB_STORE_DIR=/db/twowaykv
      - SAVE_INTERVAL=120

  graph-counties:
    image: dgoldstein1/biggraph:latest
    ports:
      - 5000:5000
    depends_on:
      - prom
    environment:
      - GRAPH_SAVE_INTERVAL=60
      - AWS_ACCESS_KEY_ID
      - AWS_DEFAULT_REGION=us-east-1
      # - AWS_GRAPH_PATH=s3://links-deployment/counties/biggraph/counties.graph
      - AWS_GRAPH_PATH=s3://links-deployment/synonyms/biggraph/current_graph.graph
      - AWS_SECRET_ACCESS_KEY
      # - AWS_SYNC_DIRECTORY=s3://links-deployment/counties/biggraph
      - AWS_SYNC_DIRECTORY=s3://links-deployment/synonyms/biggraph
      - GRAPH_SAVE_PATH=/data/counties.graph
      - USE_S3=true
  kv:
    image: dgoldstein1/twowaykv:1.0.1
    ports:
      - 5003:5001
    depends_on:
      - prom

  graph:
    image: dgoldstein1/biggraph:latest
    ports:
      - 5002:5000
    depends_on:
      - prom
    environment:
      - GRAPH_SAVE_PATH=/data/wikipedia_graph.graph
      - GRAPH_SAVE_INTERVAL=60


  ################
  ## Monitoring ##
  ################

  prom:
    image: prom/prometheus:v2.11.1
    ports:
      - 9090:9090
    entrypoint: "/bin/prometheus --web.external-url http://localhost:8443/admin/prometheus/ --web.route-prefix=/ --log.level=debug --config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:6.3.6
    volumes:
      - ./docker/grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - prom
    ports:
    - "3001:3000"
    environment:
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:/admin/grafana

 ###############
 ## Analytics ##
 ###############

  analytics-server:
    image : dgoldstein1/websiteanalytics-backend
    environment:
      - LOGGER=true
      - TEST_MODE=false
      - DATABASE_URL=mongodb://mongodb:27017
      - PORT=5000
    links:
      - mongodb
    depends_on:
      - mongodb
    ports:
      - 5005:5000

  mongodb:
    image: 'mongo:4.0.5'